config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources 'games'
  resources 'moves'
  resources 'players'
  resources 'users'
  resources 'c4_games'
  resources 'c4_moves'
  resources 'beta_home'
  resources 'uttt_games'
  resources 'roshambo_games'
  resources 'roshambo_moves'

  root to: 'home#index'

end

app/models/roshambo_game.rb
class RoshamboGame < ActiveRecord::Base

  belongs_to :player1, class_name: "User"
  belongs_to :player2, class_name: "User"
  has_many :roshambo_moves

WINNING_COMBOS = [
  ["lizard"   > "paper"   ],
  ["lizard"   > "spock"   ],
  ["paper"    > "rock"    ],
  ["paper"    > "spock"   ],
  ["rock"     > "lizard"  ],
  ["rock"     > "scissors"],
  ["scissors" > "lizard"  ],
  ["scissors" > "paper"   ],
  ["spock"    > "rock"    ],
  ["spock"    > "scissors"]
]

SHAPES = [
  [0 => "lizard"],
  [1 => "paper"],
  [2 => "rock"],
  [3 => "scissor"],
  [4 => "spock"],
]


  def make_move(player, shape)
    RoshamboMove.create(player: player, shape: shape)
  end

  def winning_move
    @roshambo_moves 
  end


end

app/controllers/roshambo_games_controller.rb
class RoshamboGamesController < ApplicationController

  def index
    @roshambo_games = RoshamboGame.all.order('id desc')
  end

  def new
    @roshambo_game = RoshamboGame.new
    @roshambo_game.player1_id = current_user.id
  end

  def create
    roshambo_game = RoshamboGame.create(roshambo_game_params)
    redirect_to(roshambo_game_path(roshambo_game))
  end

  def update
    roshambo_game = RoshamboGame.find(params[:id])
    roshambo_game.make_move(current_user, params[:square])
    redirect_to(roshambo_game_path(roshambo_game))
  end

  def show
    @roshambo_game = RoshamboGame.find(params[:id])
  end

  private
  def roshambo_game_params
    params.require(:roshambo_game).permit(:player1_id, :player2_id)
  end

end

app/views/roshambo_games/_game.html.erb
<tr class="lines">
  <td align="center", class="gamelist h"><br /><%= link_to "View Game #{game.id}", game_path(game) %></td>
  <td align="center", class="gamelist v h"><br /><%= game.player1.try(:username) %></td>
  <td align="center", class="gamelist v h"><br /><%= game.player2.try(:username) %></td>
  <td align="center", class="gamelist h"><br /><%= game.created_at.strftime("%-d %b %Y") %></td>
</tr>

app/views/roshambo_games/index.html.erb
<center>
  <br>
  <br>
  <h1>Unfortunately Roshambo is not available.</h1>
</center>

app/views/roshambo_games/new.html.erb
<center>
  <h1>Pick a Combatant!</h1>
  <br>
  <%= form_for @roshambo_game do |f| %>
  <table>
    <tr>
      <td align="right"><%= f.label :player1_id, "Player 1:" %></td>
      <td>
        <% if user_signed_in? %>
          <%= current_user.username %>
          <%= f.hidden_field :player1_id %>
        <% else %>
          <%= f.text_field :player1_id %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td align="right"><br /><%= f.label :player2_id, "Player 2:" %></td>
      <td><br /><%= f.collection_select :player2_id, User.all.reject {|user| user == current_user}, :id, :username %></td>
    </tr>
  </table>
  <br>
  <br>
  <%= f.submit "Start Game", class: "nava" %>
  <% end %>
</center>

app/views/roshambo_games/show.html.erb
<center>
  <h1>LET'S GET READY TO RUMBLE!</h1>
  <h2>
    <%= @roshambo_game.result %>
  </h2>
  <% if @roshambo_game.winning_player?(current_user) %>
    <%= audio_tag 'http://noproblo.dayjo.org/ZeldaSounds/LOZ/LOZ_Fanfare.wav', autoplay: true, controls: false %>
  <% elsif @roshambo_game.losing_player?(current_user) %>
    <%= audio_tag 'http://wompwompwomp.com/audio/sad-trombone.m4a', autoplay: true, controls: false %>
  <% else %>
    <p>Playing X, Player 1 is <%=  @roshambo_game.player1.try(:username) %> and Playing O, Player 2 is <%= @roshambo_game.player2.try(:username) %></p>
    <br>
  <% end %>
  <div id="board">
    <table>
      <tr id="row1">
        <td class="square">
          <center>
            <%= board_square_contents(@roshambo_game, 0) %>
          </center>
        </td>
        <td class="square v">
          <center>
            <%= board_square_contents(@roshambo_game, 1) %>
          </center>
        </td>
        <td class="square">
          <center>
            <%= board_square_contents(@roshambo_game, 2) %>
          </center>
        </td>
      </tr>
      <tr id="row2">
        <td class="square h">
          <center>
            <%= board_square_contents(@roshambo_game, 3) %>
          </center>
        </td>
        <td class="square v h">
          <center>
            <%= board_square_contents(@roshambo_game, 4) %>
          </center>
        </td>
        <td class="square h">
          <center>
            <%= board_square_contents(@roshambo_game, 5) %>
          </center>
        </td>
      </tr>
      <tr id="row3">
        <td class="square">
          <center>
            <%= board_square_contents(@roshambo_game, 6) %>
          </center>
        </td>
        <td class="square v">
          <center>
            <%= board_square_contents(@roshambo_game, 7) %>
          </center>
        </td>
        <td class="square">
          <center>
            <%= board_square_contents(@roshambo_game, 8) %>
          </center>
        </td>
      </tr>
    </table>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</center>