config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources 'games'
  resources 'moves'
  resources 'players'
  resources 'users'
  resources 'c4_games'
  resources 'c4_moves'
  resources 'beta_home'
  resources 'uttt_games'
  resources 'roshambo_games'
  resources 'roshambo_moves'

  root to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/views/home/index.html.erb
<center>
  <h1>Gamification Hub</h1>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <br>
  <div id="board">
    <table>
      <tr id="row1">
        <td class="square m menubuttons" >
          <% if user_signed_in? %>
            <%= link_to "Logout \n #{current_user.username}", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Login', new_user_session_path %>
          <% end %>
        </td>
        <td class="square v m menubuttons">
          <% if user_signed_in? %>
            <%= link_to 'Profile', user_path(current_user) %>
          <% else %>
            <%= link_to 'Register', new_user_registration_path %>
          <% end %>
        </td>
        <td class="square m menubuttons">
          <% if user_signed_in? %>
            <p>Following
            <i style="font-size:10px">feature unavailable</i></p>
          <% else %>
          <% end %>
        </td>
      </tr>
      <tr id="row2">
        <td class="square h m b menubuttons">
          <%= link_to 'TicTacToe Highscores', users_path %>
        </td>
        <td class="square v h m menubuttons">
          <% if user_signed_in? %>
            <%= link_to "Play Some TicTacToe", new_game_path %>
          <% else %>
            <p>Login to Play TicTacToe</p>
          <% end %>
        </td>
        <td class="square h m b menubuttons">
          <p>Tournaments
          <i style="font-size:10px">feature unavailable</i></p>
        </td>
      </tr>
      <tr id="row3">
        <td class="square m b menubuttons">
          <% if user_signed_in? %>
            <%= link_to "Beta Games", beta_home_index_path %>
          <% else %>
            <p>Login to See Beta Games</p>
          <% end %>
        </td>
        <td class="square v m menubuttons">
          <%= link_to "Spectate TicTacToe", games_path %>
        </td>
        <td class="square m menubuttons">
          <% if user_signed_in? %>
            <%= link_to "Settings", edit_user_registration_path %>
          <% else %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</center>