config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources 'games'
  resources 'moves'
  resources 'players'
  resources 'users'
  resources 'c4_games'
  resources 'c4_moves'
  resources 'beta_home'
  resources 'uttt_games'
  resources 'roshambo_games'
  resources 'roshambo_moves'

  root to: 'home#index'

end

app/controllers/beta_home_controller.rb
class BetaHomeController < ApplicationController

  def index

  end

end

app/views/beta_home/index.html.erb
<center>
  <h1>Beta Games Hub</h1>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <br>
  <div id="board">
    <table>
      <tr id="row1">
        <td class="square m menubuttons" >
          <% if user_signed_in? %>
          <%= link_to "Logout \n #{current_user.username}", destroy_user_session_path, method: :delete %>
          <% else %>
          <%= link_to 'Login', new_user_session_path %>
          <% end %>
        </td>
        <td class="square v m menubuttons">
          <% if user_signed_in? %>
          <%= link_to 'Profile', user_path(current_user) %>
          <% else %>
          <%= link_to 'Register', new_user_registration_path %>
          <% end %>
        </td>
        <td class="square m menubuttons">
          <p><i style="font-size:10px">feature coming soon</i></p>
        </td>
      </tr>
      <tr id="row2">
        <td class="square h m b menubuttons">
          <%# if user_signed_in? %>
            <%#= link_to "Connect 4", c4_games_path %>
          <%# else %>
          <p>Connect 4
          <i style="font-size:10px">feature unavailable</i></p>
          <%# end %>
        </td>
        <td class="square v h m menubuttons">
          <%# if user_signed_in? %>
            <%#= link_to "Ultimate TicTacToe", uttt_games_path %>
          <%# else %>
            <p>Ultimate TicTacToe 
            <i style="font-size:10px">feature unavailable</i></p>
          <%# end %>
        </td>
        <td class="square h m b menubuttons">
          <%# if user_signed_in? %>
            <%#= link_to "Roshambo", new_roshambo_game_path %>
          <%# else %>
          <p>Roshambo
          <i style="font-size:10px">feature unavailable</i></p>
          <%# end %>
        </td>
      </tr>
      <tr id="row3">
        <td class="square m b menubuttons">
          <%= link_to "Return to Normality", root_path %>
        </td>
        <td class="square v m menubuttons">
          <p><i style="font-size:10px">feature coming soon</i></p>
        </td>
        <td class="square m menubuttons">
          <%= link_to "Settings", edit_user_registration_path %>
        </td>
      </tr>
    </table>
  </div>
</center>